# Generated by Django 5.2.4 on 2025-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
